# Generated by Django 3.0.3 on 2020-02-18 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='language',
        ),
        migrations.AddField(
            model_name='language',
            name='lan',
            field=models.CharField(default=django.utils.timezone.now, help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)", max_length=50),
            preserve_default=False,
        ),
    ]
