# Generated by Django 3.0.3 on 2020-02-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200218_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='lan',
            field=models.CharField(default='', help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)", max_length=50),
        ),
    ]
