# Generated by Django 3.0.3 on 2020-02-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200218_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='lan',
        ),
        migrations.AddField(
            model_name='language',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('sp', 'Spanish'), ('cs', 'Chinese Simplified'), ('ct', 'Chinese Traditional')], default='cs', max_length=2),
        ),
    ]
