# Generated by Django 3.0.3 on 2020-02-19 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200219_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),), 'verbose_name': 'Book Instance', 'verbose_name_plural': 'Book Instances'},
        ),
    ]
