# Generated by Django 3.0.3 on 2020-02-09 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False, verbose_name='No.')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('intro', models.CharField(default='', max_length=511, verbose_name='Introduction')),
                ('create_date', models.DateField(null=True, verbose_name='Date of Creation')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Popularity')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'tb_subject',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False, verbose_name='No.')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('detail', models.CharField(blank=True, default='', max_length=1023, verbose_name='Details')),
                ('photo', models.CharField(default='', max_length=1023, verbose_name='Photo')),
                ('good_count', models.IntegerField(default=0, verbose_name='Good No.')),
                ('bad_count', models.IntegerField(default=0, verbose_name='Bad No.')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poll.Subject', verbose_name='Belongs to')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'tb_teacher',
            },
        ),
    ]
