# Generated by Django 3.0.3 on 2020-02-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='No.')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=32, verbose_name='Password')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='Registration Time')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'tb_user',
            },
        ),
    ]
