# Generated by Django 3.0.3 on 2020-02-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False, verbose_name='Dept No.')),
                ('name', models.CharField(max_length=20, verbose_name='Dept Name')),
                ('location', models.CharField(max_length=10, verbose_name='Dept Location')),
            ],
            options={
                'db_table': 'tb_dept',
            },
        ),
    ]
